title: Your awesome title
author: Mark Honeth
email: MHoneth@eit.ac.nz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
theme: minima

# social links
github_username:  markhoneth

show_excerpts: true # set to false to remove excerpts on the homepage
